-- Place
CREATE TABLE Place (
     placeKey       INT GENERATED BY DEFAULT AS IDENTITY,
     type           VARCHAR(50) NOT NULL,
     name           VARCHAR(100) NOT NULL,
     Place_placeKey INT,
     CONSTRAINT Place_PK PRIMARY KEY (placeKey)
);

-- Club
CREATE TABLE Club (
     clubKey        INT GENERATED BY DEFAULT AS IDENTITY,
     clubName       VARCHAR(100) NOT NULL,
     Place_placeKey INT NOT NULL,
     CONSTRAINT Club_PK PRIMARY KEY (clubKey)
);

-- Double
CREATE TABLE Double (
     doubleKey INT GENERATED BY DEFAULT AS IDENTITY,
     CONSTRAINT Double_PK PRIMARY KEY (doubleKey)
);

-- Player
CREATE TABLE Player (
     profileKey     INT GENERATED BY DEFAULT AS IDENTITY,
     firstName      VARCHAR(50) NOT NULL,
     secondName     VARCHAR(50),
     firstLastname  VARCHAR(50) NOT NULL,
     secondLastname VARCHAR(50),
     birthday       DATE,
     sex            VARCHAR(10) NOT NULL,
     photoOne       TEXT,
     photoTwo       TEXT,
     Place_placeKey INT NOT NULL,
     CONSTRAINT Player_PK PRIMARY KEY (profileKey)
);

-- Email
CREATE TABLE Email (
     emailKey          INT GENERATED BY DEFAULT AS IDENTITY,
     username          VARCHAR(100) NOT NULL,
     atSymbol          VARCHAR(5),
     domainName        VARCHAR(100) NOT NULL,
     Player_profileKey INT NOT NULL,
     CONSTRAINT Email_PK PRIMARY KEY (emailKey)
);

-- IdentityDocument
CREATE TABLE IdentityDocument (
     docKey            INT GENERATED BY DEFAULT AS IDENTITY,
     type              VARCHAR(50) NOT NULL,
     docNumber         VARCHAR(50) NOT NULL,
     Player_profileKey INT NOT NULL,
     CONSTRAINT IdentityDocument_PK PRIMARY KEY (docKey)
);
CREATE UNIQUE INDEX IdentityDocument__IDX ON IdentityDocument (Player_profileKey ASC);

-- phone
CREATE TABLE phone (
     phoneKey          INT GENERATED BY DEFAULT AS IDENTITY,
     areaCode          VARCHAR(10) NOT NULL,
     operatorCode      VARCHAR(10) NOT NULL,
     phoneNumber       VARCHAR(20) NOT NULL,
     Player_profileKey INT NOT NULL,
     CONSTRAINT phone_PK PRIMARY KEY (phoneKey)
);

-- PlayerClub
CREATE TABLE PlayerClub (
     playerClubKey     INT GENERATED BY DEFAULT AS IDENTITY,
     Player_profileKey INT NOT NULL,
     Club_clubKey      INT NOT NULL,
     CONSTRAINT PlayerClub_PK PRIMARY KEY (playerClubKey)
);

-- PlayerDouble
CREATE TABLE PlayerDouble (
     playerDoubleKey   INT GENERATED BY DEFAULT AS IDENTITY,
     Player_profileKey INT NOT NULL,
     Double_doubleKey  INT NOT NULL,
     CONSTRAINT PlayerDouble_PK PRIMARY KEY (playerDoubleKey)
);

-- Pitch
CREATE TABLE Pitch (
     pitchKey       INT GENERATED BY DEFAULT AS IDENTITY,
     pitchNumber    INT NOT NULL,
     description    TEXT,
     direction      TEXT,
     Place_placeKey INT NOT NULL,
     Club_clubKey   INT NOT NULL,
     CONSTRAINT Pitch_PK PRIMARY KEY (pitchKey)
);

-- Ranking
CREATE TABLE Ranking (
     rankingKey INT GENERATED BY DEFAULT AS IDENTITY,
     name       VARCHAR(100) NOT NULL,
     CONSTRAINT Ranking_PK PRIMARY KEY (rankingKey)
);

-- TennisCategory
CREATE TABLE TennisCategory (
     catKey             INT GENERATED BY DEFAULT AS IDENTITY,
     categoryName       VARCHAR(100) NOT NULL,
     description        TEXT,
     type               VARCHAR(50),
     Ranking_rankingKey INT NOT NULL,
     CONSTRAINT TennisCategory_PK PRIMARY KEY (catKey)
);

-- Tournament
CREATE TABLE Tournament (
     tourKey               INT GENERATED BY DEFAULT AS IDENTITY,
     tourName              VARCHAR(100) NOT NULL,
     tourDescription       TEXT,
     startDate             TIMESTAMP,
     endDate               TIMESTAMP,
     TennisCategory_catKey INT NOT NULL,
     CONSTRAINT Tournament_PK PRIMARY KEY (tourKey)
);

-- Participation (PK Simple)
CREATE TABLE Participation (
     parKey             INT GENERATED BY DEFAULT AS IDENTITY,
     startDate          TIMESTAMP,
     endDate            TIMESTAMP,
     tournamentAmount   NUMERIC(10,2) NOT NULL,
     Tournament_tourKey INT NOT NULL,
     Player_profileKey  INT,
     Double_doubleKey   INT,
     CONSTRAINT Participation_PK PRIMARY KEY (parKey)
);

-- TournamentStage (Con enlace a Torneo y recursividad Nullable)
CREATE TABLE TournamentStage (
     tournamentStageKey                 INT GENERATED BY DEFAULT AS IDENTITY,
     tournamentStageType                VARCHAR(50) NOT NULL,
     stageName                          VARCHAR(100) NOT NULL,
     Tournament_tourKey                 INT NOT NULL,
     TournamentStage_tournamentStageKey INT,
     CONSTRAINT TournamentStage_PK PRIMARY KEY (tournamentStageKey)
);

-- StageParticipation (Intermedia N:M entre Fase e Inscripción)
CREATE TABLE StageParticipation (
    stageParticipationKey              INT GENERATED BY DEFAULT AS IDENTITY,
    TournamentStage_tournamentStageKey INT NOT NULL,
    Participation_parKey               INT NOT NULL,
    CONSTRAINT StageParticipation_PK PRIMARY KEY (stageParticipationKey),
    CONSTRAINT StageParticipation_Stage_FK FOREIGN KEY (TournamentStage_tournamentStageKey)
        REFERENCES TournamentStage (tournamentStageKey) ON DELETE CASCADE,
    CONSTRAINT StageParticipation_Participation_FK FOREIGN KEY (Participation_parKey)
        REFERENCES Participation (parKey) ON DELETE CASCADE
);

-- Match
CREATE TABLE Match (
     matchKey                           INT GENERATED BY DEFAULT AS IDENTITY,
     TournamentStage_tournamentStageKey INT NOT NULL,
     CONSTRAINT Match_PK PRIMARY KEY (matchKey)
);

-- MatchStatus
CREATE TABLE MatchStatus (
     matchStatusKey    INT GENERATED BY DEFAULT AS IDENTITY,
     statusName        VARCHAR(50) NOT NULL,
     statusDescription TEXT,
     CONSTRAINT MatchStatus_PK PRIMARY KEY (matchStatusKey)
);

-- PaymentMethod
CREATE TABLE PaymentMethod (
     payMetKey  INT GENERATED BY DEFAULT AS IDENTITY,
     typeMethod VARCHAR(50) NOT NULL,
     CONSTRAINT PaymentMethod_PK PRIMARY KEY (payMetKey)
);

-- Payment
CREATE TABLE Payment (
     paymentKey              INT GENERATED BY DEFAULT AS IDENTITY,
     paymentAmount           NUMERIC(10,2) NOT NULL,
     paymentDate             TIMESTAMP NOT NULL,
     Participation_parKey    INT NOT NULL,
     PaymentMethod_payMetKey INT NOT NULL,
     bolivarExchange         NUMERIC(10,2) NOT NULL,
     transmitter             VARCHAR(100) NOT NULL,
     receptor                VARCHAR(100) NOT NULL,
     badge                   VARCHAR(50) NOT NULL,
     CONSTRAINT Payment_PK PRIMARY KEY (paymentKey)
);

-- PitchMatch
CREATE TABLE PitchMatch (
     datePitchMatch TIMESTAMP NOT NULL,
     Pitch_pitchKey INT NOT NULL,
     Match_matchKey INT NOT NULL,
     name           VARCHAR(100) NOT NULL,
     price          NUMERIC(10,2) NOT NULL,
     CONSTRAINT PitchMatch_PK PRIMARY KEY (datePitchMatch, Pitch_pitchKey, Match_matchKey)
);

-- PlayerMatch (Soporta 2 registros por partido)
CREATE TABLE PlayerMatch (
     playerMatchKey    INT GENERATED BY DEFAULT AS IDENTITY,
     matchDate         TIMESTAMP NOT NULL,
     Match_matchKey    INT NOT NULL,
     Double_doubleKey  INT,
     Player_profileKey INT,
     CONSTRAINT PlayerMatch_PK PRIMARY KEY (playerMatchKey),
     CONSTRAINT Arc_Player_Double_Check CHECK (
        ((Double_doubleKey IS NOT NULL) AND (Player_profileKey IS NULL)) OR
        ((Player_profileKey IS NOT NULL) AND (Double_doubleKey IS NULL))
     )
);

-- PlayerTennisCategory
CREATE TABLE PlayerTennisCategory (
     PlaTenCatKey          INT GENERATED BY DEFAULT AS IDENTITY,
     Player_profileKey     INT NOT NULL,
     TennisCategory_catKey INT NOT NULL,
     CONSTRAINT PlayerTennisCategory_PK PRIMARY KEY (PlaTenCatKey, Player_profileKey)
);

-- RecordStatusMatch
CREATE TABLE RecordStatusMatch (
     recordStatusMatchKey       INT GENERATED BY DEFAULT AS IDENTITY,
     dateRecordStatusMatch      TIMESTAMP NOT NULL,
     MatchStatus_matchStatusKey INT NOT NULL,
     Match_matchKey             INT NOT NULL,
     CONSTRAINT RecordStatusMatch_PK PRIMARY KEY (recordStatusMatchKey, MatchStatus_matchStatusKey, Match_matchKey)
);

-- Set
CREATE TABLE Set (
     setKey         INT GENERATED BY DEFAULT AS IDENTITY,
     setNumber      INT NOT NULL,
     gamesPlayerOne INT NOT NULL,
     gamesPlayerTwo INT NOT NULL,
     tieBreak       BOOLEAN,
     tiePlayerOne   INT,
     tiePlayerTwo   INT,
     Match_matchKey INT NOT NULL,
     superTieBreak  BOOLEAN,
     CONSTRAINT Set_PK PRIMARY KEY (setKey)
);

-- Stats (Global si Participation_parKey es NULL)
CREATE TABLE Stats (
     statsKey             INT GENERATED BY DEFAULT AS IDENTITY,
     matchesPlayed        INT DEFAULT 0 NOT NULL,
     matchesWon           INT DEFAULT 0 NOT NULL,
     matchesLost          INT DEFAULT 0 NOT NULL,
     averageMatchesWon    NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
     setsWon              INT DEFAULT 0 NOT NULL,
     setsLost             INT DEFAULT 0 NOT NULL,
     averageSetsWon       NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
     gamesWon             INT DEFAULT 0 NOT NULL,
     gamesLost            INT DEFAULT 0 NOT NULL,
     averageGamesWon      NUMERIC(5,2) DEFAULT 0.00 NOT NULL,
     Player_profileKey    INT,
     Participation_parKey INT,
     CONSTRAINT Stats_PK PRIMARY KEY (statsKey)
);

-- Verification
CREATE TABLE Verification (
     verificationKey   INT GENERATED BY DEFAULT AS IDENTITY,
     verificationDate  TIMESTAMP NOT NULL,
     Player_profileKey INT NOT NULL,
     CONSTRAINT Verification_PK PRIMARY KEY (verificationKey)
);

-- Profile
CREATE TABLE Profile (
     profileKey        INT GENERATED BY DEFAULT AS IDENTITY,
     creationDate      TIMESTAMP,
     hashPassword      TEXT,
     Email_EmailKey    INT NOT NULL,
     Player_profileKey INT,
     CONSTRAINT Profile_PK PRIMARY KEY (profileKey)
);

-- Role & RBAC
CREATE TABLE Role (
    roleKey         INT GENERATED BY DEFAULT AS IDENTITY,
    roleName        VARCHAR(100) NOT NULL,
    roleDescription TEXT,
    CONSTRAINT Role_PK PRIMARY KEY (roleKey)
);

CREATE TABLE Permission (
    permissionKey INT GENERATED BY DEFAULT AS IDENTITY,
    module        TEXT NOT NULL,
    slug          TEXT NOT NULL,
    description   TEXT NOT NULL,
    CONSTRAINT Permission_PK PRIMARY KEY (permissionKey)
);

CREATE TABLE RolePermission (
    rolePermissionKey        INT GENERATED BY DEFAULT AS IDENTITY,
    Permission_permissionKey INT NOT NULL,
    Role_roleKey             INT NOT NULL,
    CONSTRAINT RolePermission_PK PRIMARY KEY (rolePermissionKey),
    CONSTRAINT Permission_FK FOREIGN KEY (Permission_permissionKey) REFERENCES Permission (permissionKey) ON DELETE CASCADE,
    CONSTRAINT Role_FK FOREIGN KEY (Role_roleKey) REFERENCES Role (roleKey) ON DELETE CASCADE
);

CREATE TABLE ProfileRole (
    profileRoleKey     INT GENERATED BY DEFAULT AS IDENTITY,
    Profile_profileKey INT NOT NULL,
    Role_roleKey       INT NOT NULL,
    CONSTRAINT ProfileRole_PK PRIMARY KEY (profileRoleKey),
    CONSTRAINT Profile_FK FOREIGN KEY (Profile_profileKey) REFERENCES Profile (profileKey) ON DELETE CASCADE,
    CONSTRAINT Role_FK FOREIGN KEY (Role_roleKey) REFERENCES Role (roleKey) ON DELETE CASCADE
);

-- FOREIGN KEYS
ALTER TABLE Club ADD CONSTRAINT Club_Place_FK FOREIGN KEY (Place_placeKey) REFERENCES Place (placeKey);
ALTER TABLE Email ADD CONSTRAINT Email_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE IdentityDocument ADD CONSTRAINT IdentityDocument_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE Match ADD CONSTRAINT Match_TournamentStage_FK FOREIGN KEY (TournamentStage_tournamentStageKey) REFERENCES TournamentStage (tournamentStageKey) ON DELETE CASCADE;
ALTER TABLE Participation ADD CONSTRAINT Participation_Double_FK FOREIGN KEY (Double_doubleKey) REFERENCES Double (doubleKey) ON DELETE CASCADE;
ALTER TABLE Participation ADD CONSTRAINT Participation_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE Participation ADD CONSTRAINT Participation_Tournament_FK FOREIGN KEY (Tournament_tourKey) REFERENCES Tournament (tourKey) ON DELETE CASCADE;
ALTER TABLE Payment ADD CONSTRAINT Payment_Participation_FK FOREIGN KEY (Participation_parKey) REFERENCES Participation (parKey) ON DELETE CASCADE;
ALTER TABLE Payment ADD CONSTRAINT Payment_PaymentMethod_FK FOREIGN KEY (PaymentMethod_payMetKey) REFERENCES PaymentMethod (payMetKey);
ALTER TABLE phone ADD CONSTRAINT phone_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE Pitch ADD CONSTRAINT Pitch_Club_FK FOREIGN KEY (Club_clubKey) REFERENCES Club (clubKey);
ALTER TABLE Pitch ADD CONSTRAINT Pitch_Place_FK FOREIGN KEY (Place_placeKey) REFERENCES Place (placeKey);
ALTER TABLE PitchMatch ADD CONSTRAINT PitchMatch_Match_FK FOREIGN KEY (Match_matchKey) REFERENCES Match (matchKey) ON DELETE CASCADE;
ALTER TABLE PitchMatch ADD CONSTRAINT PitchMatch_Pitch_FK FOREIGN KEY (Pitch_pitchKey) REFERENCES Pitch (pitchKey);
ALTER TABLE Place ADD CONSTRAINT Place_Place_FK FOREIGN KEY (Place_placeKey) REFERENCES Place (placeKey);
ALTER TABLE Player ADD CONSTRAINT Player_Place_FK FOREIGN KEY (Place_placeKey) REFERENCES Place (placeKey);
ALTER TABLE PlayerClub ADD CONSTRAINT PlayerClub_Club_FK FOREIGN KEY (Club_clubKey) REFERENCES Club (clubKey) ON DELETE CASCADE;
ALTER TABLE PlayerClub ADD CONSTRAINT PlayerClub_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE PlayerDouble ADD CONSTRAINT PlayerDouble_Double_FK FOREIGN KEY (Double_doubleKey) REFERENCES Double (doubleKey) ON DELETE CASCADE;
ALTER TABLE PlayerDouble ADD CONSTRAINT PlayerDouble_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE PlayerMatch ADD CONSTRAINT PlayerMatch_Double_FK FOREIGN KEY (Double_doubleKey) REFERENCES Double (doubleKey) ON DELETE CASCADE;
ALTER TABLE PlayerMatch ADD CONSTRAINT PlayerMatch_Match_FK FOREIGN KEY (Match_matchKey) REFERENCES Match (matchKey) ON DELETE CASCADE;
ALTER TABLE PlayerMatch ADD CONSTRAINT PlayerMatch_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE PlayerTennisCategory ADD CONSTRAINT PlayerTennisCategory_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE PlayerTennisCategory ADD CONSTRAINT PlayerTennisCategory_TennisCategory_FK FOREIGN KEY (TennisCategory_catKey) REFERENCES TennisCategory (catKey) ON DELETE CASCADE;
ALTER TABLE RecordStatusMatch ADD CONSTRAINT RecordStatusMatch_Match_FK FOREIGN KEY (Match_matchKey) REFERENCES Match (matchKey) ON DELETE CASCADE;
ALTER TABLE RecordStatusMatch ADD CONSTRAINT RecordStatusMatch_MatchStatus_FK FOREIGN KEY (MatchStatus_matchStatusKey) REFERENCES MatchStatus (matchStatusKey);
ALTER TABLE Set ADD CONSTRAINT Set_Match_FK FOREIGN KEY (Match_matchKey) REFERENCES Match (matchKey) ON DELETE CASCADE;
ALTER TABLE Stats ADD CONSTRAINT Stats_Participation_FK FOREIGN KEY (Participation_parKey) REFERENCES Participation (parKey) ON DELETE CASCADE;
ALTER TABLE Stats ADD CONSTRAINT Stats_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE TennisCategory ADD CONSTRAINT TennisCategory_Ranking_FK FOREIGN KEY (Ranking_rankingKey) REFERENCES Ranking (rankingKey);
ALTER TABLE Tournament ADD CONSTRAINT Tournament_TennisCategory_FK FOREIGN KEY (TennisCategory_catKey) REFERENCES TennisCategory (catKey);
ALTER TABLE TournamentStage ADD CONSTRAINT TournamentStage_Tournament_FK FOREIGN KEY (Tournament_tourKey) REFERENCES Tournament (tourKey) ON DELETE CASCADE;
ALTER TABLE TournamentStage ADD CONSTRAINT TournamentStage_TournamentStage_FK FOREIGN KEY (TournamentStage_tournamentStageKey) REFERENCES TournamentStage (tournamentStageKey) ON DELETE CASCADE;
ALTER TABLE Verification ADD CONSTRAINT Verification_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
ALTER TABLE Profile ADD CONSTRAINT Profile_Email_FK FOREIGN KEY (Email_EmailKey) REFERENCES Email (emailKey) ON DELETE CASCADE;
ALTER TABLE Profile ADD CONSTRAINT Profile_Player_FK FOREIGN KEY (Player_profileKey) REFERENCES Player (profileKey) ON DELETE CASCADE;
