-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-07-30 21:18:55 VET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Club 
    ( 
     clubKey        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     clubName       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Place_placeKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Club 
    ADD CONSTRAINT Club_PK PRIMARY KEY ( clubKey ) ;

CREATE TABLE Double 
    ( 
     doubleKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Double 
    ADD CONSTRAINT Double_PK PRIMARY KEY ( doubleKey ) ;

CREATE TABLE Email 
    ( 
     emailKey          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     username          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     atSymbol          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     domainName        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Email 
    ADD CONSTRAINT Email_PK PRIMARY KEY ( emailKey ) ;

CREATE TABLE IdentityDocument 
    ( 
     docKey            UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     type              UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     docNumber         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;
CREATE UNIQUE INDEX IdentityDocument__IDX ON IdentityDocument 
    ( 
     Player_profileKey ASC 
    ) 
;

ALTER TABLE IdentityDocument 
    ADD CONSTRAINT IdentityDocument_PK PRIMARY KEY ( docKey ) ;

CREATE TABLE Match 
    ( 
     matchKey                           UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     TournamentStage_tournamentStageKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Match 
    ADD CONSTRAINT Match_PK PRIMARY KEY ( matchKey ) ;

CREATE TABLE MatchStatus 
    ( 
     matchStatusKey    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     statusName        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     statusDescription UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    
    ) 
;

ALTER TABLE MatchStatus 
    ADD CONSTRAINT MatchStatus_PK PRIMARY KEY ( matchStatusKey ) ;

CREATE TABLE Participation 
    ( 
     parKey             UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     startDate          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     endUpdate          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Tournament_tourKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     tournamentAmount   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Double_doubleKey   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Participation 
    ADD CONSTRAINT Participation_PK PRIMARY KEY ( parKey, Tournament_tourKey ) ;

CREATE TABLE Payment 
    ( 
     paymentKey                       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     paymentAmount                    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     paymentDate                      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Participation_parKey             UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Participation_Tournament_tourKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     PaymentMethod_payMetKey          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     bolivarExchange                  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     transmitter                      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     receptor                         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     badge                            UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_PK PRIMARY KEY ( paymentKey, Participation_parKey, Participation_Tournament_tourKey, PaymentMethod_payMetKey ) ;

CREATE TABLE PaymentMethod 
    ( 
     payMetKey  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     typeMethod UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE PaymentMethod 
    ADD CONSTRAINT PaymentMethod_PK PRIMARY KEY ( payMetKey ) ;

CREATE TABLE phone 
    ( 
     phoneKey          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     areaCode          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     operatorCode      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     phoneNumber       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE phone 
    ADD CONSTRAINT phone_PK PRIMARY KEY ( phoneKey ) ;

CREATE TABLE Pitch 
    ( 
     pitchKey       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     pitchNumber    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     description    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     direction      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Place_placeKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Club_clubKey   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Pitch 
    ADD CONSTRAINT Pitch_PK PRIMARY KEY ( pitchKey ) ;

CREATE TABLE PitchMatch 
    ( 
     "date"         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     price          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Pitch_pitchKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     name           UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Match_matchKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE PitchMatch 
    ADD CONSTRAINT PitchMatch_PK PRIMARY KEY ( "date", Pitch_pitchKey, name, Match_matchKey ) ;

CREATE TABLE Place 
    ( 
     placeKey       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     type           UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     name           UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Place_placeKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Place 
    ADD CONSTRAINT Place_PK PRIMARY KEY ( placeKey ) ;

CREATE TABLE Player 
    ( 
     profileKey     UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     firstName      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     secondName     UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     firstLastname  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     secondLastname UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     birthday       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     sex            UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     photoOne       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     photoTwo       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Place_placeKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Player 
    ADD CONSTRAINT Player_PK PRIMARY KEY ( profileKey ) ;

CREATE TABLE PlayerClub 
    ( 
     playerClubKey     UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Club_clubKey      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE PlayerClub 
    ADD CONSTRAINT PlayerClub_PK PRIMARY KEY ( playerClubKey, Player_profileKey, Club_clubKey ) ;

CREATE TABLE PlayerDouble 
    ( 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Double_doubleKey  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE PlayerDouble 
    ADD CONSTRAINT PlayerDouble_PK PRIMARY KEY ( Player_profileKey, Double_doubleKey ) ;

CREATE TABLE PlayerMatch 
    ( 
     matchDate         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Match_matchKey    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Double_doubleKey  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    
    ) 
;
ALTER TABLE PlayerMatch 
    ADD CONSTRAINT Arc_3 CHECK ( 
        (  (Double_doubleKey IS NOT NULL) AND 
         (Player_profileKey IS NULL) ) OR 
        (  (Player_profileKey IS NOT NULL) AND 
         (Double_doubleKey IS NULL) )  ) 
;

ALTER TABLE PlayerMatch 
    ADD CONSTRAINT PlayerMatch_PK PRIMARY KEY ( Match_matchKey ) ;

CREATE TABLE PlayerTennisCategory 
    ( 
     PlaTenCatKey                     UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey                UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     TennisCategory_TennisCategory_ID UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE PlayerTennisCategory 
    ADD CONSTRAINT PlayerTennisCategory_PK PRIMARY KEY ( PlaTenCatKey, Player_profileKey ) ;

CREATE TABLE Ranking 
    ( 
     rankingKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     name       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Ranking 
    ADD CONSTRAINT Ranking_PK PRIMARY KEY ( rankingKey ) ;

CREATE TABLE RecordStatusMatch 
    ( 
     recordStatusMatchKey       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     "date"                     UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     MatchStatus_matchStatusKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Match_matchKey             UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE RecordStatusMatch 
    ADD CONSTRAINT RecordStatusMatch_PK PRIMARY KEY ( recordStatusMatchKey, MatchStatus_matchStatusKey, Match_matchKey ) ;

CREATE TABLE "Set" 
    ( 
     setKey         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     setNumber      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     gamesPlayerOne UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     gamesPlayerTwo UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     tieBreak       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     tiePlayerOne   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     tiePlayerTwo   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Match_matchKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     superTieBreak  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    
    ) 
;

ALTER TABLE "Set" 
    ADD CONSTRAINT Set_PK PRIMARY KEY ( setKey ) ;

CREATE TABLE Stats 
    ( 
     statsKey                         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     matchesPlayed                    UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     matchesWon                       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     matchesLost                      UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     averageMatchesWon                UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     setsWon                          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     setsLost                         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     averageSetsWon                   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     gamesWon                         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     gamesLost                        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     averageGamesWon                  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey                UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Participation_parKey             UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Participation_Tournament_tourKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Stats__IDX ON Stats 
    ( 
     Player_profileKey ASC 
    ) 
;
CREATE UNIQUE INDEX Stats__IDXv1 ON Stats 
    ( 
     Participation_parKey ASC , 
     Participation_Tournament_tourKey ASC 
    ) 
;

ALTER TABLE Stats 
    ADD CONSTRAINT Stats_PK PRIMARY KEY ( statsKey ) ;

CREATE TABLE TennisCategory 
    ( 
     catKey             UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     categoryName       UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     description        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     type               UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     Ranking_rankingKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     TennisCategory_ID  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE TennisCategory 
    ADD CONSTRAINT TennisCategory_PK PRIMARY KEY ( TennisCategory_ID ) ;

CREATE TABLE Tournament 
    ( 
     tourKey                          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     tourName                         UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     tourDescription                  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     startDate                        UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
     endDate                          UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                    , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     TennisCategory_TennisCategory_ID UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Tournament 
    ADD CONSTRAINT Tournament_PK PRIMARY KEY ( tourKey ) ;

CREATE TABLE TournamentStage 
    ( 
     tournamentStageKey                 UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     tournamentStageType                UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     name                               UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     TournamentStage_tournamentStageKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Participation_parKey               UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Participation_Tournament_tourKey   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE TournamentStage 
    ADD CONSTRAINT TournamentStage_PK PRIMARY KEY ( tournamentStageKey ) ;

CREATE TABLE Verification 
    ( 
     verificationKey   UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     verificationDate  UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL , 
     Player_profileKey UNKNOWN 
--  ERROR: Datatype UNKNOWN is not allowed 
                     NOT NULL 
    ) 
;

ALTER TABLE Verification 
    ADD CONSTRAINT Verification_PK PRIMARY KEY ( verificationKey ) ;

ALTER TABLE Club 
    ADD CONSTRAINT Club_Place_FK FOREIGN KEY 
    ( 
     Place_placeKey
    ) 
    REFERENCES Place 
    ( 
     placeKey
    ) 
;

ALTER TABLE Email 
    ADD CONSTRAINT Email_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE IdentityDocument 
    ADD CONSTRAINT IdentityDocument_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE Match 
    ADD CONSTRAINT Match_TournamentStage_FK FOREIGN KEY 
    ( 
     TournamentStage_tournamentStageKey
    ) 
    REFERENCES TournamentStage 
    ( 
     tournamentStageKey
    ) 
;

ALTER TABLE Participation 
    ADD CONSTRAINT Participation_Double_FK FOREIGN KEY 
    ( 
     Double_doubleKey
    ) 
    REFERENCES Double 
    ( 
     doubleKey
    ) 
;

ALTER TABLE Participation 
    ADD CONSTRAINT Participation_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE Participation 
    ADD CONSTRAINT Participation_Tournament_FK FOREIGN KEY 
    ( 
     Tournament_tourKey
    ) 
    REFERENCES Tournament 
    ( 
     tourKey
    ) 
;

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_Participation_FK FOREIGN KEY 
    ( 
     Participation_parKey,
     Participation_Tournament_tourKey
    ) 
    REFERENCES Participation 
    ( 
     parKey,
     Tournament_tourKey
    ) 
;

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_PaymentMethod_FK FOREIGN KEY 
    ( 
     PaymentMethod_payMetKey
    ) 
    REFERENCES PaymentMethod 
    ( 
     payMetKey
    ) 
;

ALTER TABLE phone 
    ADD CONSTRAINT phone_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE Pitch 
    ADD CONSTRAINT Pitch_Club_FK FOREIGN KEY 
    ( 
     Club_clubKey
    ) 
    REFERENCES Club 
    ( 
     clubKey
    ) 
;

ALTER TABLE Pitch 
    ADD CONSTRAINT Pitch_Place_FK FOREIGN KEY 
    ( 
     Place_placeKey
    ) 
    REFERENCES Place 
    ( 
     placeKey
    ) 
;

ALTER TABLE PitchMatch 
    ADD CONSTRAINT PitchMatch_Match_FK FOREIGN KEY 
    ( 
     Match_matchKey
    ) 
    REFERENCES Match 
    ( 
     matchKey
    ) 
;

ALTER TABLE PitchMatch 
    ADD CONSTRAINT PitchMatch_Pitch_FK FOREIGN KEY 
    ( 
     Pitch_pitchKey
    ) 
    REFERENCES Pitch 
    ( 
     pitchKey
    ) 
;

ALTER TABLE Place 
    ADD CONSTRAINT Place_Place_FK FOREIGN KEY 
    ( 
     Place_placeKey
    ) 
    REFERENCES Place 
    ( 
     placeKey
    ) 
;

ALTER TABLE Player 
    ADD CONSTRAINT Player_Place_FK FOREIGN KEY 
    ( 
     Place_placeKey
    ) 
    REFERENCES Place 
    ( 
     placeKey
    ) 
;

ALTER TABLE PlayerClub 
    ADD CONSTRAINT PlayerClub_Club_FK FOREIGN KEY 
    ( 
     Club_clubKey
    ) 
    REFERENCES Club 
    ( 
     clubKey
    ) 
;

ALTER TABLE PlayerClub 
    ADD CONSTRAINT PlayerClub_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE PlayerDouble 
    ADD CONSTRAINT PlayerDouble_Double_FK FOREIGN KEY 
    ( 
     Double_doubleKey
    ) 
    REFERENCES Double 
    ( 
     doubleKey
    ) 
;

ALTER TABLE PlayerDouble 
    ADD CONSTRAINT PlayerDouble_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE PlayerMatch 
    ADD CONSTRAINT PlayerMatch_Double_FK FOREIGN KEY 
    ( 
     Double_doubleKey
    ) 
    REFERENCES Double 
    ( 
     doubleKey
    ) 
;

ALTER TABLE PlayerMatch 
    ADD CONSTRAINT PlayerMatch_Match_FK FOREIGN KEY 
    ( 
     Match_matchKey
    ) 
    REFERENCES Match 
    ( 
     matchKey
    ) 
;

ALTER TABLE PlayerMatch 
    ADD CONSTRAINT PlayerMatch_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE PlayerTennisCategory 
    ADD CONSTRAINT PlayerTennisCategory_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE PlayerTennisCategory 
    ADD CONSTRAINT PlayerTennisCategory_TennisCategory_FK FOREIGN KEY 
    ( 
     TennisCategory_TennisCategory_ID
    ) 
    REFERENCES TennisCategory 
    ( 
     TennisCategory_ID
    ) 
;

ALTER TABLE RecordStatusMatch 
    ADD CONSTRAINT RecordStatusMatch_Match_FK FOREIGN KEY 
    ( 
     Match_matchKey
    ) 
    REFERENCES Match 
    ( 
     matchKey
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE RecordStatusMatch 
    ADD CONSTRAINT RecordStatusMatch_MatchStatus_FK FOREIGN KEY 
    ( 
     MatchStatus_matchStatusKey
    ) 
    REFERENCES MatchStatus 
    ( 
     matchStatusKey
    ) 
;

ALTER TABLE "Set" 
    ADD CONSTRAINT Set_Match_FK FOREIGN KEY 
    ( 
     Match_matchKey
    ) 
    REFERENCES Match 
    ( 
     matchKey
    ) 
;

ALTER TABLE Stats 
    ADD CONSTRAINT Stats_Participation_FK FOREIGN KEY 
    ( 
     Participation_parKey,
     Participation_Tournament_tourKey
    ) 
    REFERENCES Participation 
    ( 
     parKey,
     Tournament_tourKey
    ) 
;

ALTER TABLE Stats 
    ADD CONSTRAINT Stats_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

ALTER TABLE TennisCategory 
    ADD CONSTRAINT TennisCategory_Ranking_FK FOREIGN KEY 
    ( 
     Ranking_rankingKey
    ) 
    REFERENCES Ranking 
    ( 
     rankingKey
    ) 
;

ALTER TABLE Tournament 
    ADD CONSTRAINT Tournament_TennisCategory_FK FOREIGN KEY 
    ( 
     TennisCategory_TennisCategory_ID
    ) 
    REFERENCES TennisCategory 
    ( 
     TennisCategory_ID
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE TournamentStage 
    ADD CONSTRAINT TournamentStage_Participation_FK FOREIGN KEY 
    ( 
     Participation_parKey,
     Participation_Tournament_tourKey
    ) 
    REFERENCES Participation 
    ( 
     parKey,
     Tournament_tourKey
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE TournamentStage 
    ADD CONSTRAINT TournamentStage_TournamentStage_FK FOREIGN KEY 
    ( 
     TournamentStage_tournamentStageKey
    ) 
    REFERENCES TournamentStage 
    ( 
     tournamentStageKey
    ) 
;

ALTER TABLE Verification 
    ADD CONSTRAINT Verification_Player_FK FOREIGN KEY 
    ( 
     Player_profileKey
    ) 
    REFERENCES Player 
    ( 
     profileKey
    ) 
;

CREATE SEQUENCE TennisCategory_TennisCategory_ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER TennisCategory_TennisCategory_ 
BEFORE INSERT ON TennisCategory 
FOR EACH ROW 
WHEN (NEW.TennisCategory_ID IS NULL) 
BEGIN 
    :NEW.TennisCategory_ID := TennisCategory_TennisCategory_.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            26
-- CREATE INDEX                             3
-- ALTER TABLE                             62
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                 140
-- WARNINGS                                 0
